spring:
  application:
    name: user-system
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 日志配置（通用）
logging:
  include-application-name: false
  level:
    root: INFO
  file:
    name: logs/user-system.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 30

# MyBatis-Plus 配置（通用）
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
